import React from 'react';
import { FormControl, FormGroup, FormControlLabel, Checkbox, Box, Typography, Paper } from '@mui/material';

const FilterTable = ({ filters, handleFilterChange }) => {
  return (
    <Paper sx={{ width: '100%', padding: '1rem', boxSizing: 'border-box', backgroundColor: '#f5f5f5', borderRadius: '8px' }}>
      <Typography variant="h6" gutterBottom>Filter by Ingredient</Typography>
      <FormControl component="fieldset">
        <Box sx={{ marginBottom: '1rem' }}>
          <Typography variant="subtitle1">Meats</Typography>
          <FormGroup>
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.chicken}
                  onChange={handleFilterChange}
                  name="chicken"
                  color="primary"
                />
              }
              label="Chicken"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.fish}
                  onChange={handleFilterChange}
                  name="fish"
                  color="primary"
                />
              }
              label="Fish"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.beef}
                  onChange={handleFilterChange}
                  name="beef"
                  color="primary"
                />
              }
              label="Beef"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.pork}
                  onChange={handleFilterChange}
                  name="pork"
                  color="primary"
                />
              }
              label="Pork"
            />
          </FormGroup>
        </Box>
        <Box sx={{ marginBottom: '1rem' }}>
          <Typography variant="subtitle1">Diets</Typography>
          <FormGroup>
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.vegetarian}
                  onChange={handleFilterChange}
                  name="vegetarian"
                  color="primary"
                />
              }
              label="Vegetarian"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.vegan}
                  onChange={handleFilterChange}
                  name="vegan"
                  color="primary"
                />
              }
              label="Vegan"
            />
          </FormGroup>
        </Box>
        <Box sx={{ marginBottom: '1rem' }}>
          <Typography variant="subtitle1">Vegetables</Typography>
          <FormGroup>
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.carrot}
                  onChange={handleFilterChange}
                  name="carrot"
                  color="primary"
                />
              }
              label="Carrot"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.broccoli}
                  onChange={handleFilterChange}
                  name="broccoli"
                  color="primary"
                />
              }
              label="Broccoli"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.spinach}
                  onChange={handleFilterChange}
                  name="spinach"
                  color="primary"
                />
              }
              label="Spinach"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.tomato}
                  onChange={handleFilterChange}
                  name="tomato"
                  color="primary"
                />
              }
              label="Tomato"
            />
          </FormGroup>
        </Box>
        <Box sx={{ marginBottom: '1rem' }}>
          <Typography variant="subtitle1">Fruits</Typography>
          <FormGroup>
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.apple}
                  onChange={handleFilterChange}
                  name="apple"
                  color="primary"
                />
              }
              label="Apple"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.banana}
                  onChange={handleFilterChange}
                  name="banana"
                  color="primary"
                />
              }
              label="Banana"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.orange}
                  onChange={handleFilterChange}
                  name="orange"
                  color="primary"
                />
              }
              label="Orange"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.strawberry}
                  onChange={handleFilterChange}
                  name="strawberry"
                  color="primary"
                />
              }
              label="Strawberry"
            />
          </FormGroup>
        </Box>
        <Box sx={{ marginBottom: '1rem' }}>
          <Typography variant="subtitle1">Categories</Typography>
          <FormGroup>
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.dessert}
                  onChange={handleFilterChange}
                  name="dessert"
                  color="primary"
                />
              }
              label="Dessert"
            />
            <FormControlLabel
              control={
                <Checkbox
                  checked={filters.breakfast}
                  onChange={handleFilterChange}
                  name="breakfast"
                  color="primary"
                />
              }
              label="Breakfast"
            />
          </FormGroup>
        </Box>
      </FormControl>
    </Paper>
  );
};

export default FilterTable;